import { PostResponseType } from "@/app/types";

export const dummyPosts: PostResponseType[] = [
  {
    id: 1,
    title: "게시글 제목 ~ test ~ ",
    content:
      "게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test게시글 내용 ~ test",
    createdAt: "2021-09-20T00:00:00",
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "윤승휘",
      createdAt: String(new Date()),
    },
  },
  {
    id: 2,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 3,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 4,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 5,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 6,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 7,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
  {
    id: 8,
    title: "게시글 제목",
    content: "게시글 내용 ~",
    createdAt: String(new Date()),
    mainImage: process.env.NEXT_PUBLIC_NONE_IMAGE!,
    userId: "test",
    user: {
      id: 1,
      userId: "user_id",
      profile: process.env.NEXT_PUBLIC_NONE_USER!,
      role: "user",
      nickname: "user_nickname",
      createdAt: String(new Date()),
    },
  },
];
